[tool.poetry]
name = "wordle"
version = "0.1.0"
description = ""
authors = ["Saulo Leão <sleaojr@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
rich = "^11.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
